# Description
# ===========
# Enable required repos and install Globus Connect Server

- name: Setup Globus 
  hosts: globus
  user: centos

  #shell: "if test nohup.out; then rm -f nohup.out;fi && nohup /usr/sbin/globus-connect-server login localhost &> nohup.out && grep https nohup.out"
  tasks:
        - name: Install tk 
          dnf:
                name: tk 
                state: latest
          become: True
          when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

        - name: Install tcllib
          dnf:
                name: tcllib
                state: latest
          become: True
          when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

        - name: Retrieve GCP for Linux via WGet
          get_url: url=https://downloads.globus.org/globus-connect-personal/linux/stable/globusconnectpersonal-latest.tgz dest=~/

        - name: Extract GCP tarball
          shell: "tar -xvzf ~/globusconnectpersonal-latest.tgz"

