# Description
# ===========
# Enable required repos and install Globus Connect Server

- name: Setup Globus 
  hosts: globus
  user: centos

  #shell: "if test nohup.out; then rm -f nohup.out;fi && nohup /usr/sbin/globus-connect-server login localhost &> nohup.out && grep https nohup.out"
  tasks:
        - name: Install PIP
          dnf:
                name: python3-pip
                state: latest
          become: True
          when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

        - name: Install pipx
          pip:
            name: pipx
          become: True

        - name: Install Globus-CLI
          shell: "pipx install globus-cli"

